// Printable / PDF-able end-of-day Z-report.
// Opens a clean print window; the browser's "Save as PDF" turns it into a file.
import type { ShiftReport } from "@/lib/shift-report";
import { formatCurrency } from "@/lib/format";

export type ZReportExtras = {
  shopName?: string;
  expenses?: number;
  expenseLines?: Array<{ label: string; amount: number }>;
};

export function zReportHtml(r: ShiftReport, extra: ZReportExtras = {}): string {
  const shop = extra.shopName ?? "TillPoint";
  const expenses = extra.expenses ?? 0;
  const cash = r.by_payment["cash"] ?? 0;
  const rows = Object.entries(r.by_payment)
    .map(
      ([k, v]) =>
        `<tr><td style="text-transform:capitalize">${k}</td><td class="r">${formatCurrency(v)}</td></tr>`,
    )
    .join("");
  const expLines = (extra.expenseLines ?? [])
    .map((e) => `<tr><td>${e.label}</td><td class="r">-${formatCurrency(e.amount)}</td></tr>`)
    .join("");

  return `<!doctype html><html><head><meta charset="utf-8" />
<title>Z-Report ${new Date(r.closed_at).toLocaleDateString()}</title>
<style>
  *{box-sizing:border-box}
  body{font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:#0f172a;margin:0;padding:32px;background:#fff}
  .wrap{max-width:720px;margin:0 auto;border:1px solid #dbeafe;border-radius:14px;padding:28px}
  h1{font-size:22px;margin:0 0 2px}
  .sub{color:#64748b;font-size:12px;margin-bottom:18px}
  h2{font-size:13px;text-transform:uppercase;letter-spacing:.08em;color:#2563eb;margin:22px 0 8px}
  table{width:100%;border-collapse:collapse;font-size:14px}
  td{padding:6px 0;border-bottom:1px dashed #e2e8f0}
  .r{text-align:right;font-variant-numeric:tabular-nums}
  .total td{border-top:2px solid #0f172a;border-bottom:none;font-weight:700;font-size:16px;padding-top:10px}
  .foot{margin-top:26px;font-size:11px;color:#94a3b8;text-align:center}
  .sig{margin-top:34px;display:flex;gap:28px}
  .sig div{flex:1;border-top:1px solid #94a3b8;padding-top:6px;font-size:11px;color:#64748b}
  @media print{body{padding:0}.wrap{border:none}}
</style></head><body><div class="wrap">
  <h1>${shop} — Z-Report (End of day)</h1>
  <div class="sub">
    Closed ${new Date(r.closed_at).toLocaleString()} &middot; Opened ${new Date(r.opened_at).toLocaleString()}<br/>
    Operator: ${r.cashier_name} &middot; Sales: ${r.sale_count}
  </div>

  <h2>Sales by payment type</h2>
  <table>${rows || `<tr><td>No sales</td><td class="r">${formatCurrency(0)}</td></tr>`}
    <tr class="total"><td>Total sales</td><td class="r">${formatCurrency(r.total)}</td></tr>
  </table>

  <h2>Cash reconciliation</h2>
  <table>
    <tr><td>Cash sales</td><td class="r">${formatCurrency(cash)}</td></tr>
    ${expLines}
    <tr><td>Expenses paid from drawer</td><td class="r">-${formatCurrency(expenses)}</td></tr>
    <tr><td>Expected in drawer</td><td class="r">${formatCurrency(cash - expenses)}</td></tr>
    <tr><td>Counted cash</td><td class="r">${r.counted_cash === null ? "n/a" : formatCurrency(r.counted_cash)}</td></tr>
    <tr class="total"><td>Variance</td><td class="r">${r.variance === null ? "n/a" : formatCurrency(r.variance)}</td></tr>
  </table>

  ${r.note ? `<h2>Note</h2><div style="font-size:13px">${r.note}</div>` : ""}

  <div class="sig"><div>Cashier signature</div><div>Manager signature</div></div>
  <div class="foot">Tax rate: 0% &middot; Generated by TillPoint on ${new Date().toLocaleString()}</div>
</div>
<script>window.onload = function(){ setTimeout(function(){ window.print(); }, 250); };</script>
</body></html>`;
}

export function printZReport(r: ShiftReport, extra: ZReportExtras = {}): void {
  const win = window.open("", "_blank", "width=820,height=900");
  if (!win) return;
  win.document.write(zReportHtml(r, extra));
  win.document.close();
}

export function downloadZReport(r: ShiftReport, extra: ZReportExtras = {}): void {
  const blob = new Blob([zReportHtml(r, extra)], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `z-report-${r.closed_at.slice(0, 10)}.html`;
  a.click();
  URL.revokeObjectURL(url);
}
