WITH d(pname,cat,vname,price) AS (VALUES
('Crystal Mints','Sweets','1 sweet',0.05),
('Crystal Mints','Sweets','7 sweets',0.25),
('Crystal Mints','Sweets','10 sweets (7 + 3)',0.40),
('Crystal Mints','Sweets','18 sweets (14 + 4)',0.70),
('Crystal Mints','Sweets','28 sweets',1.00),
('Dandy Pink Gum','Sweets','1 sweet',0.05),
('Dandy Pink Gum','Sweets','7 sweets',0.25),
('Dandy Pink Gum','Sweets','10 sweets (7 + 3)',0.40),
('Dandy Pink Gum','Sweets','18 sweets (14 + 4)',0.70),
('Dandy Pink Gum','Sweets','28 sweets',1.00),
('Toffee','Sweets','1 sweet',0.05),
('Toffee','Sweets','7 sweets',0.25),
('Toffee','Sweets','10 sweets (7 + 3)',0.40),
('Toffee','Sweets','18 sweets (14 + 4)',0.70),
('Toffee','Sweets','28 sweets',1.00),
('Toffee Bar','Sweets','2 bars',0.25),
('Stambo Lollipop','Sweets','1 lollipop',0.10),
('Stambo Lollipop','Sweets','2 lollipops',0.25),
('Stambo Lollipop','Sweets','5 lollipops',0.50),
('Stambo Lollipop','Sweets','10 lollipops',1.00),
('Big Boom Lollipop','Sweets','1 lollipop',0.10),
('Big Boom Lollipop','Sweets','2 lollipops',0.25),
('Big Boom Lollipop','Sweets','5 lollipops',0.50),
('Big Boom Lollipop','Sweets','10 lollipops',1.00),
('Eclair Lollipop','Sweets','1 lollipop',0.10),
('Eclair Lollipop','Sweets','2 lollipops',0.25),
('Eclair Lollipop','Sweets','5 lollipops',0.50),
('Eclair Lollipop','Sweets','10 lollipops',1.00),
('Yogeta Lollipop','Sweets','1 lollipop',0.10),
('Yogeta Lollipop','Sweets','2 lollipops',0.25),
('Yogeta Lollipop','Sweets','5 lollipops',0.50),
('Yogeta Lollipop','Sweets','10 lollipops',1.00),
('Cigarettes - Mint','Tobacco','1 box',0.50),
('Cigarettes - Pegasus','Tobacco','1 box',0.50),
('Cigarettes - Flame','Tobacco','1 box',0.50),
('Cigarettes - Storm','Tobacco','1 cigarette',0.05),
('Cigarettes - Storm','Tobacco','5 cigarettes',0.25),
('Cigarettes - Storm','Tobacco','10 cigarettes',0.50),
('Cigarettes - Storm','Tobacco','1 box',1.00),
('Cigarettes - Everest','Tobacco','1 cigarette',0.06),
('Cigarettes - Everest','Tobacco','4 cigarettes',0.25),
('Cigarettes - Everest','Tobacco','8 cigarettes',0.50),
('Cigarettes - Everest','Tobacco','Box less 4 cigarettes',1.00),
('Cigarettes - Everest','Tobacco','1 box',1.25),
('Cigarettes - Madison','Tobacco','1 cigarette',0.06),
('Cigarettes - Madison','Tobacco','4 cigarettes',0.25),
('Cigarettes - Madison','Tobacco','8 cigarettes',0.50),
('Cigarettes - Madison','Tobacco','Box less 4 cigarettes',1.00),
('Cigarettes - Madison','Tobacco','1 box',1.25),
('Cerevita','Breakfast','Corn & Wheat',3.00),
('Instant Porridge','Breakfast','Standard',1.50),
('Instant Cereal','Breakfast','Standard',2.00),
('Cornflakes','Breakfast','Kellogg''s',2.00),
('Rice 2kg','Groceries','Mr Rice (White)',2.00),
('Rice 2kg','Groceries','Mr Rice (Parboiled)',2.00),
('Rice 2kg','Groceries','Raha (White)',2.00),
('Rice 2kg','Groceries','Raha (Parboiled)',2.00),
('Rice 2kg','Groceries','Top Chef',2.00),
('Rice 2kg','Groceries','Mahatma',2.00),
('Rice 2kg','Groceries','Cook More',2.00),
('Rice 5kg','Groceries','Mr Rice (White)',5.00),
('Rice 5kg','Groceries','Raha (White)',5.00),
('Rice 5kg','Groceries','Basmati',10.50),
('Rice 5kg','Groceries','Cook More',5.25),
('Flour','Groceries','Mega (All Purpose)',2.00),
('Flour','Groceries','Mega (Self-Raising)',2.00),
('Flour','Groceries','Gloria (Self-Raising)',2.00),
('Sugar','Groceries','GoldStar',3.00),
('Sugar','Groceries','Huletts',2.70),
('Sugar','Groceries','Tapitapi',2.60),
('Spaghetti','Groceries','Bela 50g',0.50),
('Cooking Oil 2 Litres','Groceries','Zimgold',3.50),
('Cooking Oil 2 Litres','Groceries','Olivine',3.50),
('Cooking Oil 2 Litres','Groceries','Puredrop',3.50),
('Cooking Oil 2 Litres','Groceries','Golden Glow',3.30),
('Cooking Oil D''lite','Groceries','750ml',1.50),
('Cooking Oil D''lite','Groceries','375ml',1.00),
('Rabroy 500ml','Groceries','Standard',1.50),
('Salad Cream 750ml','Groceries','Standard',3.00),
('Karinga','Groceries','Standard',0.50),
('Royco','Groceries','Beef',0.50),
('Royco','Groceries','Chicken',0.50),
('Knorr Soup','Groceries','Standard',0.50),
('Jam','Groceries','Sun Jam',1.50),
('Jam','Groceries','Marmalade Jam',1.75),
('Tinned Fish','Groceries','Lucky Star',1.00),
('Tinned Beef','Groceries','Bull Brand',2.00),
('Baked Beans','Groceries','Monty''s',1.00),
('Baked Beans','Groceries','Koo',1.00),
('Baked Beans','Groceries','Cashel',1.00),
('Baked Beans','Groceries','Tomco',1.00),
('Tomato Sauce','Groceries','Standard',1.00),
('Vinegar','Groceries','Standard',1.00),
('Chilli','Groceries','Small',1.00),
('Chilli','Groceries','Big',1.50),
('Dovi','Groceries','Small',1.00),
('Dovi','Groceries','Big',3.00),
('Aromat','Groceries','Standard',1.00),
('Black Soil Mealie Meal','Groceries','5kg',3.00),
('Black Soil Mealie Meal','Groceries','10kg',5.00),
('Matches','Household','1 box',0.05),
('Matches','Household','5 boxes',0.25),
('Matches','Household','1 carton',0.50),
('Candle','Household','1 candle',0.25),
('Fresh Milk 1 Litre','Dairy','Chimombe',1.00),
('Fresh Milk 1 Litre','Dairy','Dandairy',1.00),
('Fresh Milk 250ml','Dairy','Standard',1.00),
('Chocolate Milk 250ml','Dairy','Standard',0.50),
('Steri Milk','Dairy','Standard',1.00),
('Everyday Powdered Milk','Dairy','Standard',3.50),
('Cremora','Dairy','Sachet',1.75),
('Cremora','Dairy','Box',3.50),
('Ellis Brown','Dairy','Sachet',1.75),
('Ellis Brown','Dairy','Box',3.50),
('Yoghurt','Dairy','Standard',0.50),
('Buttermilk','Dairy','Standard',0.50),
('Butter','Dairy','Buttercup Small',1.00),
('Butter','Dairy','Buttercup Big',2.00),
('Eggs','Dairy','3 eggs',0.50),
('Eggs','Dairy','6 eggs',1.00),
('Eggs','Dairy','1 crate',4.50),
('Milk-It','Dairy','Standard',0.50),
('Baker''s Inn Bread','Bakery','1 loaf',1.00),
('Unbranded Bread','Bakery','1 loaf',0.50),
('Unbranded Bread','Bakery','2 loaves',1.00),
('Pork Pie','Bakery','Standard',0.50),
('Big Bites','Bakery','Standard',0.50),
('Matemba','Snacks','50g',0.50),
('Matemba','Snacks','100g',1.00),
('Mega Snax','Snacks','Small 100g',0.25),
('Mega Snax','Snacks','Big 150g',0.50),
('Things Chips','Snacks','Standard',0.50),
('Smiley Chips','Snacks','1 chip',0.05),
('Smiley Chips','Snacks','3 chips',0.15),
('Smiley Chips','Snacks','5 chips',0.25),
('Smiley Chips','Snacks','10 chips',0.50),
('Smiley Chips','Snacks','1 pack',1.00),
('Chungs','Snacks','Small',0.50),
('Chungs','Snacks','Big',1.00),
('Popcorn','Snacks','Standard',1.00),
('Maputi (Red Package)','Snacks','1 unit',0.05),
('Maputi (Red Package)','Snacks','5 units',0.25),
('Maputi (Red Package)','Snacks','10 units',0.50),
('Maputi (Red Package)','Snacks','1 pack',1.00),
('Maputi (Blue Package)','Snacks','1 pack',1.00),
('Chocolate','Snacks','Mint Crisp',0.50),
('Chocolate','Snacks','Milk',0.50),
('Cadbury Chocolate','Snacks','Top Deck',1.00),
('Cadbury Chocolate','Snacks','Fruit & Nut',1.00),
('Cadbury Chocolate','Snacks','Milk',1.00),
('Cookies - Ramba Waraira','Snacks','250g',1.00),
('Cookies - Ramba Waraira','Snacks','500g',1.50),
('Cookies - Ramba Waraira','Snacks','1kg',3.00),
('Cream Biscuits','Snacks','Bermuda',0.50),
('Cream Biscuits','Snacks','Lemon',0.50),
('Loose Biscuits','Snacks','YumYum',0.50),
('Shortbread Biscuits','Snacks','Standard',0.50),
('Tea Time Biscuits','Snacks','Standard',0.50),
('Jumbo Chips','Snacks','Beef - 1 packet',0.25),
('Jumbo Chips','Snacks','Beef - 2 packets',0.50),
('Jumbo Chips','Snacks','Beef - 1 pack',2.50),
('Jumbo Chips','Snacks','Fruit Chutney - 1 packet',0.25),
('Jumbo Chips','Snacks','Fruit Chutney - 2 packets',0.50),
('Jumbo Chips','Snacks','Fruit Chutney - 1 pack',2.50),
('Jumbo Chips','Snacks','Cream n'' Cheese - 1 packet',0.25),
('Jumbo Chips','Snacks','Cream n'' Cheese - 2 packets',0.50),
('Jumbo Chips','Snacks','Cream n'' Cheese - 1 pack',2.50),
('Jumbo Chips','Snacks','BBQ - 1 packet',0.25),
('Jumbo Chips','Snacks','BBQ - 2 packets',0.50),
('Jumbo Chips','Snacks','BBQ - 1 pack',2.50),
('Jumbo Chips','Snacks','Mexican Chili - 1 packet',0.25),
('Jumbo Chips','Snacks','Mexican Chili - 2 packets',0.50),
('Jumbo Chips','Snacks','Mexican Chili - 1 pack',2.50),
('Kellogg''s Noodles','Groceries','Beef - 3 packets',1.00),
('Kellogg''s Noodles','Groceries','Beef - 1 pack',1.50),
('Kellogg''s Noodles','Groceries','Chicken - 3 packets',1.00),
('Kellogg''s Noodles','Groceries','Chicken - 1 pack',1.50),
('Kellogg''s Noodles','Groceries','Durban Curry - 3 packets',1.00),
('Kellogg''s Noodles','Groceries','Durban Curry - 1 pack',1.50),
('Revive Juice','Beverages','250ml',0.25),
('Revive Juice','Beverages','500ml',0.50),
('Revive Juice','Beverages','1 Litre',1.00),
('Cool Splash 5 Litres','Beverages','Raspberry',4.00),
('Cool Splash 5 Litres','Beverages','Cream Soda',4.00),
('Cool Splash 5 Litres','Beverages','Blackberry',4.00),
('Cool Splash 5 Litres','Beverages','Orange',4.00),
('Baseline 5 Litres','Beverages','Raspberry',3.50),
('Baseline 5 Litres','Beverages','Cream Soda',3.50),
('Baseline 5 Litres','Beverages','Blackberry',3.50),
('Baseline 5 Litres','Beverages','Orange',3.50),
('Swish-Up 5 Litres','Beverages','Raspberry',2.00),
('Swish-Up 5 Litres','Beverages','Cream Soda',2.00),
('Swish-Up 5 Litres','Beverages','Blackberry',2.00),
('Swish-Up 5 Litres','Beverages','Orange',2.00),
('Mazoe 2 Litres','Beverages','Raspberry',3.00),
('Mazoe 2 Litres','Beverages','Cream Soda',3.00),
('Mazoe 2 Litres','Beverages','Peach',3.00),
('Mazoe 2 Litres','Beverages','Blackberry',3.50),
('Mazoe 2 Litres','Beverages','Orange Crush',4.00),
('Coca Cola','Beverages','2 Litres',2.00),
('Coca Cola','Beverages','440ml',0.50),
('Fanta','Beverages','2 Litres',2.00),
('Sparkle','Beverages','2 Litres',1.00),
('Z&G Mineral Water','Beverages','500ml',0.25),
('Z&G Mineral Water','Beverages','2 Litres',0.50),
('Z&G Mineral Water','Beverages','5 Litres',1.00),
('Wildcat Drink','Beverages','Standard',0.50),
('Tembeya Drink','Beverages','Standard',0.50),
('Captain Gingerwise Drink','Beverages','Standard',0.50),
('Ricoffy','Beverages','Small',1.50),
('Ricoffy','Beverages','Big',3.00),
('Tea Bags','Beverages','Stella',0.50),
('Tea Bags','Beverages','Quick Brew',1.00),
('Toast Leaf','Beverages','Standard',0.25),
('Satiskin Body Lotion','Personal Care','2 Litres Coconut',4.50),
('Satiskin Body Lotion','Personal Care','2 Litres Lavender',4.50),
('Satiskin Body Lotion','Personal Care','2 Litres Wild Rose',4.50),
('Satiskin Body Lotion','Personal Care','2 Litres Peach Blossom',4.50),
('Satiskin Body Lotion','Personal Care','2 Litres Luxurious',5.00),
('Satiskin Body Lotion','Personal Care','1 Litre',2.25),
('Bath Soap','Personal Care','Geisha',1.00),
('Bath Soap','Personal Care','Lux',1.00),
('Bath Soap','Personal Care','Protex',1.00),
('Bath Soap','Personal Care','Dettol',1.00),
('Bath Soap','Personal Care','Lifebuoy',1.00),
('Bath Soap','Personal Care','Hi-Life',0.50),
('Bath Soap','Personal Care','Romance',0.60),
('Bath Soap','Personal Care','Jade',0.80),
('Cleancloud Body Wash','Personal Care','Standard',3.50),
('Colgate','Personal Care','Standard',1.00),
('Toothbrush','Personal Care','Standard',0.50),
('Hair Food','Personal Care','Standard',1.00),
('Hair Remover','Personal Care','Standard',0.50),
('Isoplus Hair Spray','Personal Care','Standard',2.00),
('Roll On','Personal Care','Nivea',2.00),
('Roll On','Personal Care','Shower to Shower',1.00),
('Razor (Gillette)','Personal Care','1 box',0.50),
('Razor (Gillette)','Personal Care','2 blades',0.25),
('Vaseline','Personal Care','50ml',0.50),
('Vaseline','Personal Care','100ml',1.00),
('Vaseline','Personal Care','250ml',2.50),
('Vaseline Baby Crez','Personal Care','Standard',2.00),
('Skala','Personal Care','Carrot',1.00),
('Skala','Personal Care','For Men',1.00),
('Clere (For Men)','Personal Care','Ice',3.00),
('Clere (For Men)','Personal Care','Fire',3.00),
('Clere Nourishing Body Cream','Personal Care','Standard',2.00),
('Epimax','Personal Care','Baby & Junior',5.50),
('Epimax','Personal Care','Original Cream',5.50),
('Cuettie','Personal Care','Small - 1 packet',1.00),
('Cuettie','Personal Care','Medium - 1 packet',1.00),
('Cuettie','Personal Care','Large - 1 packet',1.00),
('Cuettie','Personal Care','Extra Large - 1 packet',1.00),
('Softcare','Personal Care','Small - 1 packet',1.00),
('Softcare','Personal Care','Small - 1 pack',4.50),
('Softcare','Personal Care','Medium - 1 packet',1.00),
('Softcare','Personal Care','Medium - 1 pack',4.50),
('Softcare','Personal Care','Large - 1 packet',1.00),
('Softcare','Personal Care','Large - 1 pack',4.50),
('Softcare','Personal Care','Extra Large - 1 packet',1.00),
('Softcare','Personal Care','Extra Large - 1 pack',4.50),
('Tissue (Two Ply)','Household','1 roll',0.50),
('Tissue (Two Ply)','Household','2 rolls',1.00),
('Tissue (Two Ply)','Household','18-roll pack',9.00),
('MAQ Washing Powder','Household','2kg',5.00),
('Aloha Washing Powder','Household','2kg',4.50),
('Aloha Washing Powder','Household','1kg',2.50),
('Aloha Washing Powder','Household','500g',1.25),
('Boom Washing Powder','Household','2kg',4.50),
('Boom Washing Powder','Household','1kg',2.50),
('Boom Washing Powder','Household','500g',1.25),
('Washing Soap','Household','Perfection',1.50),
('Washing Soap','Household','Big Ben',1.50),
('Boom Paste','Household','Standard',0.50),
('Handy Andy','Household','Standard',2.00),
('Domestos','Household','Standard',2.00),
('Sunlight Dish Wash 750ml','Household','Standard',2.00),
('Boom Dish Washer 750ml','Household','Standard',2.00),
('Sauber 2 Litres','Household','Standard',2.00),
('Knock-Out 2 Litres','Household','Standard',2.00),
('Air Freshener Spray','Household','Standard',2.00),
('Doom Spray','Household','Standard',2.00),
('Air Wick Spray','Household','Standard',2.00),
('Ruler','Stationery','Standard',0.50),
('Pencil','Stationery','Standard',0.25),
('Pen','Stationery','Standard',0.25),
('Plastic Cover','Stationery','Standard',0.50),
('Khaki Cover','Stationery','Standard',0.50),
('32-Page Exercise Book','Stationery','Standard',0.25),
('72-Page Exercise Book','Stationery','Standard',0.25),
('Graph Book','Stationery','Standard',1.00),
('1 Quire Book','Stationery','Standard',1.00),
('2 Quire Book','Stationery','Standard',1.00)
),
ip AS (
  INSERT INTO public.products (name, category, base_price)
  SELECT pname, min(cat), min(price) FROM d GROUP BY pname RETURNING id, name
)
INSERT INTO public.product_variants (product_id, variant_name, price)
SELECT ip.id, d.vname, d.price FROM d JOIN ip ON ip.name = d.pname;

UPDATE public.stock SET quantity = 40, low_stock_alert_level = 5;